marmoym/marmoym-api

- src/routes/v1/index.ts
- src/routes/v1/termRoute.ts
- src/routes/v1/userRoute.ts
- src/services/ModelService.ts
> routes to be refactored

- src/controllers/v1/DefinitionController/DefinitionController.ts
- src/controllers/v1/TermController/TermController.ts
- src/controllers/v1/UsageController/UsageController.ts
- src/controllers/v1/UserController/UserController.ts
> Controllers to be refactored

- .gitignore
- .vscode/settings.json
> Include .vscode/settings.json that hints code styles

- src/constants/ErrorType/UserError.ts
- src/constants/ErrorType/index.ts
- src/controllers/User/UserSignInController.ts
- src/models/MarmoymError.ts
- src/routes/v1/testRoute.ts
- src/services/errorHandleService.ts
#29
MarmoymError is an object that represents errors defined
in Marmoym. ErrorType is predefined types of MarmoymError.
This commit replaces error throwings within UserSignInController.
> Add MarmoymError and ErrorType

- README.md
> Add overall description and a number of categories in README.md

- .travis.yml
- package.json
> Add .travis.yml

- src/controllers/Definition/DefinitionAddController.ts
- src/controllers/Term/TermGetController.ts
- src/dao/Definition/DefinitionSelectDAO.ts
- src/dao/Origin/OriginSelectDAO.ts
- src/dao/Pos/PosSelectDAO.ts
- src/dao/Term/TermSelectDAO.ts
- src/dao/Term/TermUpdateDAO.ts
- src/dao/Usage/UsageSelectDAO.ts
- src/database/migrations/20171001192003_initial.js
- src/models/TermStatus.ts
- src/routes/RequestTypes.ts
- src/routes/URL.ts
- src/routes/v1/definitionRoute.ts
- src/routes/v1/index.ts
- src/routes/v1/termRoute.ts
> Add functionality that show definitions recently

- src/controllers/Definition/DefinitionGetController.ts
- src/dao/Definition/DefinitionSelectDAO.ts
- src/dao/Term/TermSelectDAO.ts
- src/models/ErrorType/TermError.ts
- src/models/ErrorType/index.ts
- src/routes/RequestTypes.ts
- src/routes/URL.ts
- src/routes/v1/definitionRoute.ts
> Add api that returns definitions by termid

- src/routes/ResponseTypes.ts
> Create ResponseTypes describing DefinitionGetResponse, etc

- internals/pm2/pm2.config.js
- internals/shell/setup.sh
- package.json
Add get_config() in setup.sh
#106
> Add `deploy:dev` in script of package.json

- src/routes/URL.ts
- src/routes/v1/definitionRoute.ts
- src/routes/v1/userRoute.ts
> Modify api URLs so that it better complies with RESTful concepts

- src/models/ResponseCode.ts
- src/services/responseService.ts
> Allow named response object from apis

- src/controllers/Definition/DefinitionGetController.ts
- src/dao/Definition/DefinitionSelectDAO.ts
- src/dao/Term/TermSelectDAO.ts
- src/routes/RequestTypes.ts
- src/routes/v1/definitionRoute.ts
> Add api that returns definition searched by term

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> Update Pull request template and contributing.md

- package.json
- src/controllers/Definition/DefinitionGetController.ts
- src/routes/ResponseTypes.ts
https://github.com/tymsai/marmoym-api/issues/128
Controllers
- Commit message to follow [commit message guideline](https://github.com/tymsai/marmoym-api/blob/dev/CONTRIBUTING.md#commit-messages)
> Refactor DefinitionGetController trimming Promise.all()'s

- src/controllers/Definition/DefinitionGetController.ts
controllers
- Commit message to follow [commit message guideline](https://github.com/tymsai/marmoym-api/blob/dev/CONTRIBUTING.md#commit-messages)
> Hotfix getDefinitionByDefIds() so that users is properly returned

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- Commit message to follow [commit message guideline](https://github.com/tymsai/marmoym-api/blob/dev/CONTRIBUTING.md#commit-messages)
> Update PR template and CONTRIBUTING.md

- src/controllers/Definition/DefinitionGetController.ts
- src/routes/RequestTypes.ts
- src/routes/v1/definitionRoute.ts
- src/routes/v1/userRoute.ts
> `RequestTypes` have been refactored, stripped of namespaces

- .gitignore
- package.json
- src/database/index.js
- src/database/knexfile.js
- src/modules/logger.js
> Create and set `logger` of `winston` instances

- src/modules/logger.js
> Modify logger to log to file only when `production`

- src/app.ts
> Remove winston global settings out of `app.ts`

- package.json
- src/utils/StringUtils.ts
>  Redefine `clean` script to use `rimraf` and modify `build`

- src/controllers/User/UserDeleteController.ts
- src/controllers/User/UserGetController.ts
- src/controllers/User/UserSignInController.ts
- src/controllers/User/UserSignUpController.ts
- src/controllers/User/UserUpdateController.ts
- src/models/ErrorType/index.ts
- src/services/authService.ts
> Categorize `ErrorType` with 3-letter code

- package.json
- tslint.json
> Add `tslint` and configuration

- package.json
> Remove dependency `pm2`

- src/controllers/Definition/DefinitionGetController.ts
- src/middlewares/paramValidator/requestHandlers/definitionRequest.ts
- src/middlewares/paramValidator/validate.ts
- src/models/ApiResult/GetDefinitionsResult.ts
- src/models/RequestParams/GetDefinitionsParam.ts
- src/routes/v1/definitionRoute.ts
> Refactor request handling for `ApiURL.DEFINITIONS`, `POST`

- src/models/ApiURL.ts
- src/routes/v1/userRoute.ts
> Modify ApiURL for `user` functionalities

- package.json
- src/app.ts
> Add `morgan` as logger

- tslint.json
> Upgrade tslint.json to 0.0.1

- src/middlewares/paramValidator/validate.ts
- src/models/ErrorType/MiscErrorType.ts
> Add ErrorType `REQUEST_TYPE_UNKNOWN`

- src/middlewares/paramValidator/requestHandlers/definitionRequest.ts
> Add param validator for `ApiURL.DEFINITIONS_IDS`, `GET`

- src/middlewares/paramValidator/validate.ts
> Create _removeTrailingSlash to trim trailing slash in request URL

- package.json
> Correct script `start:dev:debug` to run `dist/app.js` properly

- src/middlewares/paramValidator/requestHandlers/definitionRequest.ts
- src/models/RequestParams/GetDefinitionsParam.ts
> Make `defIds` of GetDefinitionsParam optional

- src/controllers/Definition/DefinitionGetController.ts
- src/dao/Definition/DefinitionSelectDAO.ts
- src/middlewares/paramValidator/requestHandlers/definitionRequest.ts
- src/models/RequestParams/GetDefinitionIdsParam.ts
- src/models/RequestParams/GetDefinitionsParam.ts
- src/routes/v1/definitionRoute.ts
GetDefinitionIdsParam is created.
#191
> Make `getDefinitionIds()` process `defIds` in param

- .travis.yml
> Add `linting` in Travis build chain

- src/constants/Entity.ts
- src/daos/Definition/DefinitionInsertDAO.ts
- src/daos/Definition/DefinitionSelectDAO.ts
- src/daos/Origin/OriginInsertDAO.ts
- src/daos/Origin/OriginSelectDAO.ts
- src/daos/Pos/PosSelectDAO.ts
- src/daos/Term/TermInsertDAO.ts
- src/daos/Term/TermSelectDAO.ts
- src/daos/Term/TermUpdateDAO.ts
- src/daos/Usage/UsageInsertDAO.ts
- src/daos/Usage/UsageSelectDAO.ts
- src/daos/User/UserDeleteDAO.ts
- src/daos/User/UserInsertDAO.ts
- src/daos/User/UserSelectDAO.ts
- src/daos/User/UserUpdateDAO.ts
> Create constant `Entity` that has entity names of DB

- src/constants/ApiURL.ts
- src/constants/Field.ts
- src/constants/index.ts
- src/controllers/User/UserSignInController.ts
- src/daos/User/UserSelectDAO.ts
- src/middlewares/paramValidator/requestHandler.ts
- src/middlewares/paramValidator/requestHandlers/userRequest.ts
- src/models/RequestParam/SignInUserParam.ts
- src/routes/v1/definitionRoute.ts
- src/routes/v1/userRoute.ts
> Create param validator for `URL.SESSION_NEW`

- src/routes/v1/userRoute.ts
> Create name of returning token as `token`

- src/constants/ResponseCode.ts
- src/controllers/User/UserSignUpController.ts
- src/middlewares/paramValidator/requestHandlers/userRequest.ts
- src/models/RequestParam/SignUpUserParam.ts
- src/modules/respond.ts
- src/routes/v1/userRoute.ts
This commit also refactors  to correctly return
string data type.
#213
> Amend userSignUp functionality

- package.json
Fixes https://github.com/marmoym/marmoym-api/issues/223
> chore: add nodemon as dependency and update script `start:devi`

- internals/shell/setup.sh
Fixes https://github.com/marmoym/marmoym-api/issues/226
#226
> chore: update endpoint for `marmoym-config`

- src/database/seeds/data/development/pos.ts
- src/database/seeds/definition.ts
- src/database/seeds/pos.ts
- src/database/seeds/term.ts
- src/database/seeds/user.ts
> feat: update entity names

- src/database/entities/Comment.ts
- src/database/entities/CommentPath.ts
> feat: add comment entity
